In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns

url = 'https://drive.google.com/uc?id=1cCkwiVv4mgfl20ntgY3n4yApcWqqZQe6'
df = pd.read_csv(url)

df.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [5]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
df.shape

(4803, 24)

# Feature Engineering

In [7]:
# Using   genres , keywords , cast , director  , orginal_language , runtime

In [8]:
selected_features = ["genres" ,"keywords"  , "original_language" , "cast" , "director" ,"runtime" ]

In [9]:
selected_features

['genres', 'keywords', 'original_language', 'cast', 'director', 'runtime']

In [10]:
new_data = df[selected_features]


In [20]:
new_data.fillna("" , inplace=True)
new_data.isna().sum()
# new_data.head()

/var/folders/fd/2d33_ptj5sndr1qwvq88fzc40000gn/T/ipykernel_75208/1015503087.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data.fillna("" , inplace=True)


genres               0
keywords             0
original_language    0
cast                 0
director             0
runtime              0
dtype: int64

# Converting the text data to numeric using TfidfVectorizer

In [21]:
vectorizer = TfidfVectorizer()

In [22]:
# TfidfVectorizer() can only be applied on 1d hence this step:-
combined_data = (
    new_data['genres'] + ' ' +
    new_data['keywords'] + ' ' +
    new_data['original_language'] + ' ' +
    new_data['cast'] + ' ' +
    new_data['director']
) 

In [23]:
combined_data

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  en Edward Burns Kerry Bish\u00...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      en Daniel Henney Eliza Coupe Bill Paxton Ala...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [24]:
feature_vector = vectorizer.fit_transform(combined_data)

In [26]:
print(feature_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 102348 stored elements and shape (4803, 14868)>
  Coords	Values
  (0, 86)	0.08502902364077554
  (0, 144)	0.09827307248858284
  (0, 4442)	0.12012539827085397
  (0, 11761)	0.11206402612776616
  (0, 4573)	0.11219522632812938
  (0, 3119)	0.23117155461447458
  (0, 2618)	0.2425925833210578
  (0, 4893)	0.1982420314391392
  (0, 12403)	0.3766735943238939
  (0, 14256)	0.13883081597626543
  (0, 2758)	0.2697284654771739
  (0, 12316)	0.2353052695326346
  (0, 4168)	0.03734352846690744
  (0, 11533)	0.16260042698137087
  (0, 14582)	0.2554982568835541
  (0, 14843)	0.21826588105197825
  (0, 11506)	0.2353052695326346
  (0, 12150)	0.22256873370821875
  (0, 14312)	0.21443342131163756
  (0, 12584)	0.16372359523879906
  (0, 7505)	0.24540176320809434
  (0, 8840)	0.17353590912089953
  (0, 11232)	0.20989860473942398
  (0, 6551)	0.1224234125135496
  (0, 2063)	0.1866518649944755
  :	:
  (4801, 5852)	0.322455239802952
  (4801, 253)	0.19806508189922148
 

In [27]:
similarity = cosine_similarity(feature_vector)

In [29]:
print(similarity)

[[1.         0.02820855 0.04616569 ... 0.00128325 0.00152922 0.00127856]
 [0.02820855 1.         0.01627439 ... 0.01762654 0.00131869 0.00110253]
 [0.04616569 0.01627439 1.         ... 0.0013247  0.06723507 0.00131986]
 ...
 [0.00128325 0.01762654 0.0013247  ... 1.         0.00140718 0.0266944 ]
 [0.00152922 0.00131869 0.06723507 ... 0.00140718 1.         0.00140204]
 [0.00127856 0.00110253 0.00131986 ... 0.0266944  0.00140204 1.        ]]


In [33]:
similarity.shape

(4803, 4803)

In [37]:
movie_name = input("Enter Your Favourite movie name")

Enter Your Favourite movie name iron man


In [40]:
all_title_list  = df["title"].tolist()

In [43]:
# print(all_title_list)

In [44]:
import difflib
difflib.get_close_matches(movie_name , all_title_list)

['Iron Man', 'Iron Man 3', 'Iron Man 2']

In [45]:
close_match = difflib.get_close_matches(movie_name , all_title_list)[0]

In [75]:
close_match

'Iron Man'

In [77]:
matched_rows = df[df.title == close_match]
if not matched_rows.empty:
    index = matched_rows["index"].values[0]
    print(index)
else:
    print("NOT FOUND")

68
